### ISSUE TITLE
Use TegraRCMSmash GUI instead

### ISSUE THREAD

**Issue by bmn001** [noirscape/SwitchGuide#11]
On this page:
https://switchguide.xyz/os-specific-preparations/windows.html

You can rip out the parts about batch files and Zadig if you direct people to use TegraRcmGUI instead of TegraRCMSmash:
https://github.com/eliboa/TegraRcmGUI/releases

One app needed instead of two, basically.

TegraRcmGUI has a one-click button to install the correct driver (so no zadig needed), and a one-click GUI button to send a Hekate payload (so no batch files needed).

**Comment by noirscape** [comment]
One question before I try looking into this: Does the user need to download the Hekate files themselves when using TegraRCMSmash GUI?

**Comment by bmn001** [comment]
Yes.  They'll need to provide one file to the GUI on their PC - hekate_ctcaer_4.2.bin (as of today) - from this zip archive https://github.com/CTCaer/hekate/releases and TegraRcmGUI will send it

**Comment by noirscape** [comment]
After that it's just opening and clicking one button?

**Comment by bmn001** [comment]
I mean...you can run it yourself and see :)

Some screenshots are here-
https://gbatemp.net/threads/tegrarcmgui-simple-gui-for-tegrarcmsmash.503510/

To install the driver, click the settings tab and hit the Install Driver button.

To select and send the payload, use the payload tab, select the file, then click the Inject Payload button.


Separately, this app also has the benefit of showing you whether or not you're currently in RCM mode (red icon at bottom vs green icon)

**Comment by noirscape** [comment]
@bmn001 - Ah, I see. Are payloads automatically added to favorites/is the first payload in the favorites automatically selected?

I'm asking since Windows isn't my daily driver (it's linux) and as a result I have little experience with running this from Windows.

**Comment by bmn001** [comment]
It comes bundled with only one payload - ReiNX.bin.

To add another payload to the Favorites list, you first enter the path to the new one in the "Select payload" box, then click the + button.

**Comment by noirscape** [comment]
Would it be possible to modify the bundled payload? I want to prevent users from accidentally running ReiNX and getting their Switch banned.

**Comment by bmn001** [comment]
Yes.  It's just stored as a bin file.  You can tell them not to use it, or to just delete it.
