### ISSUE TITLE
Error 2002-6001 when launching CFW

### ISSUE THREAD

**Issue by TMi4** [noirscape/SwitchGuide#18]
Just followed the guide and everything worked out flawlessly until I launched Atmosphere. I see the Switch Home screen for a second, then this error appears:

![img_20181205_202921](https://user-images.githubusercontent.com/10154186/49539340-b563c980-f8cd-11e8-88b8-722c1fa9b1df.jpg)

When running the error code through Google nothing turns up, but similar reports in [this thread](https://gbatemp.net/threads/how-to-use-hekate-4-2-with-atmosphere-0-8-x-on-6-2-firmware.524998/) suggest that the most recent version of Atmosphere (which the guide points to) might not work with the stock 3.0.1 FW of my Switch.

**Comment by noirscape** [comment]
This issue should have been opened on [Atmosphere-NX/Atmosphere](https://github.com/Atmosphere-NX/Atmosphere/issues)'s issue tracker instead. Please provide full information as requested there.

Make sure to include all of the following in your report on the tracker:

- Filesystem information (FAT32/exFAT, size, SD class)
- The crash log associated with it (can be found in `/atmosphere/crash_logs`)
- Any additional KIPs you might be loading (**try running without loading any KIPs in first before opening the issue**).

**Comment by TMi4** [comment]
I thought the guide might want to reflect that you might have to update your FW or point compatible Atmosphere releases for different FWs, which is why I posted here.

Edit: Following guide.sdsetup.com worked. They use Atmosphere 0.7.5 in their SD package. So yeah, maybe you want to put a note somewhere regarding this.

**Comment by noirscape** [comment]
Again, open the issue on Atmosphere's repository. I don't know what you want me to do here.

You're the only person that I know of that has done this guide on 3.0.1 that has run into issues with it (and I know you're not the only person on 3.x that has followed my guide, I had people open issues about sys-ftpd not working).

Open the issue on Atmospheres repository.
