### ISSUE TITLE
Cant find Atmosphere when going to "Launch" in Hekate.

### ISSUE THREAD

**Issue by ghost** [noirscape/SwitchGuide#2]
I did everything right.
Nothing is out of place and is where it should be from the guide.
But when I go to launch CFW, it cant find Atmosphere.

Is there something I am doing wrong?

**Comment by SanktyRG** [comment]
> I did everything right.
> Nothing is out of place and is where it should be from the guide.
> But when I go to launch CFW, it cant find Atmosphere.
> 
> Is there something I am doing wrong?

I had this problem and then noticed that the 'hekate_ipl' file had '.ini.txt' extension, I just renamed it to '.ini' and it is now working perfectly.

**Comment by noirscape** [comment]
Added a warning/notice about browsers appending `.txt`.

Feel free to reopen if this does not end up fixing the issue.
