### ISSUE TITLE
Poweroff (RCM) or reboot (RCM)

### ISSUE THREAD

**Issue by ziggurism** [noirscape/SwitchGuide#26]
Step 9 of "Dumping your console keys" at https://switchguide.xyz/keydump.html says "Select Poweroff (RCM). This will make your Switch power on in RCM mode automatically on the next boot."

but on my instance there is no "poweroff (RCM)", there are only "reboot (RCM)", "reboot normal", and "power off". I assume the former is what is intended?

**Comment by noirscape** [comment]
The former, adjusting right now, those instructions were written from the top of my head.

Thanks for spotting!
