### ISSUE TITLE
[ERROR] Fatal error: Failed to stat stage2 (fusee-secondary.bin)!

### ISSUE THREAD

**Issue by RyabDev** [noirscape/SwitchGuide#29]
Followed the guide exactly with the latest atmosphere 8.2 and I get then when selecting it in hekate

**Comment by noirscape** [comment]
Is fusee-secondary.bin in the `atmosphere` folder?

**Comment by RyabDev** [comment]
Yes both primary and secondary my switch is running 5.1.0 too

**Comment by noirscape** [comment]
exFAT or FAT32?

**Comment by RyabDev** [comment]
exFAT

**Comment by noirscape** [comment]
Try using FAT32 instead, exFAT sometimes has issues with Homebrew.

**Comment by RyabDev** [comment]
give me a bit of time need to backup my Nintendo folder seeing it has games in it

**Comment by RyabDev** [comment]
Managed to resolve the issue myself it appears its an issue with Hekate on 5.1.0

**Comment by noirscape** [comment]
Alrighty then. Closing this issue.
