### ISSUE TITLE
At some levels of magnification, the command to install python on the Mac Prep page is cut off by the sidebar

### ISSUE THREAD

**Issue by dude8513** [noirscape/SwitchGuide#3]
Title. The attached screenshot was taken at 100% magnification (the default) on Firefox in MacOS
<img width="1074" alt="screen shot 2018-10-18 at 8 57 42 am" src="https://user-images.githubusercontent.com/17957568/47156019-1e5a9800-d2b4-11e8-8b15-d13595e8efa8.png">

**Comment by noirscape** [comment]
Thanks and fixed, please let me know if you encounter any other issues.
