### ISSUE TITLE
sys-ftpd.kip shouldn't be included with Atmosphere if it boot on 1.0.0

### ISSUE THREAD

**Issue by Hayato213** [noirscape/SwitchGuide#4]
Hey Noirscape just to point out that sys-ftpd.kip shouldn't be included on 1.0.0 or it will just crash if it was running fuse-primary.bin. I fixed the problem by asking SciresM. You can close the issue, just pointing out. 

![img_20181022_150837](https://user-images.githubusercontent.com/37278480/47315223-f2bc1280-d611-11e8-8391-7c02c1cdb412.jpg)

**Comment by noirscape** [comment]
I added a notice about `sys-ftpd` on 1.0.0 to the 1.0.0 instructions. Thanks for noticing this (I don't own a 1.0.0 Switch, so I can't verify this by myself.)

If you run into any other issues, feel free to make a new issue on the tracker, these really do help.

**Comment by becausewat** [comment]
This also affects 3.0.0

**Comment by noirscape** [comment]
Expanded notice to count for systems on 3.0.0 as well as new entry in universal FAQ for it.

If this fails on other/higher firmwares please let me know.
